In [25]:
import pandas as pd
import numpy as np

In [26]:
pluie = pd.read_csv("pluie.csv", sep = ',')

In [27]:
temperature = pd.read_csv("temperature.csv", sep = ',|;')

C:\Users\Dell\Miniconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [28]:
temperature.head()

    date  mini  terrain  maxi  moyenne
0  01/14    -4       13    40       29
1  01/15   -11       11    33       15
2  01/15    -7       28    40       20
3  01/15    -1       33    18       18
4  01/17   -11       38    29       28

In [29]:
cond = temperature.moyenne > temperature.maxi
temperature.loc[cond, ['moyenne', 'maxi']] = temperature.loc[cond, ['maxi', 'moyenne']].values

In [30]:
temperature

      date  mini  terrain  maxi  moyenne
0    01/14    -4       13    40       29
1    01/15   -11       11    33       15
2    01/15    -7       28    40       20
3    01/15    -1       33    18       18
4    01/17   -11       38    29       28
5    01/15    -9       38    36       29
6    01/15   -11       56    38       13
7    01/15    -7       58    41       24
8    01/15    -2       99    31       14
9    01/16   -12        6    26       21
10   01/16   -14       30    38       20
11   01/16   -13       44    28       18
12   01/16   -14       75    45       13
13   01/16     1       98    25       24
14   01/17    -2       28    25       24
15   01/17    -2       65    42       17
16   01/17     0       65    29       23
17   01/17    -1       79    29       26
18   01/18   -12       20    32       16
19   01/19   -13       19    44       17
20   01/19     0       20    33       23
21   01/19   -12       28    35       22
22   01/19     1       29    32       27
23   01/19   -15       52    46       11
24   01/19    -8       99    21       12
25   02/14    -2       74    27       16
26   02/15     1       19    46       16
27   02/15    -8       36    38       21
28   02/16    -5       34    45       23
29   02/16   -13       55    39       14
..     ...   ...      ...   ...      ...
870  03/15    -8       28    44       25
871  02/17     1       12    27       22
872  09/18   -10       73    32       25
873  08/14    -1       76    29       25
874  03/14    -4       25    27       21
875  12/16     2       43    20       18
876  07/17    -2        7    37       22
877  09/16     0       11    19       13
878  12/19     1       76    20       13
879  08/18   -13       23    30       12
880  02/17    -8       23    28       17
881  03/16    -2       61    21       10
882  12/19    -6       21    28       10
883  09/19   -10        8    18       17
884  05/14     0       21    42       27
885  07/18    -9        4    38       15
886  03/18    -6       94    40       10
887  06/15     0       23    26       13
888  01/17    -7       18    13       12
889  02/16   -15       72    14       11
890  01/14    -5       66    11       10
891  01/14     2       72    46       19
892  10/18    -8       50    43       24
893  05/19    -9       89    25       17
894  09/16   -10        8    26       19
895  02/16   -13       17    38       28
896  10/14     0       55    16       15
897  09/16   -15       19    35       12
898  03/19    -4       63    26       11
899  06/17    -1       18    44       24

[900 rows x 5 columns]

In [31]:
temperature['moyenne'].loc[temperature['moyenne'] == temperature['maxi']] = ((temperature['maxi'] + temperature['mini'])/2)
temperature

C:\Users\Dell\Miniconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

      date  mini  terrain  maxi  moyenne
0    01/14    -4       13    40     29.0
1    01/15   -11       11    33     15.0
2    01/15    -7       28    40     20.0
3    01/15    -1       33    18      8.5
4    01/17   -11       38    29     28.0
5    01/15    -9       38    36     29.0
6    01/15   -11       56    38     13.0
7    01/15    -7       58    41     24.0
8    01/15    -2       99    31     14.0
9    01/16   -12        6    26     21.0
10   01/16   -14       30    38     20.0
11   01/16   -13       44    28     18.0
12   01/16   -14       75    45     13.0
13   01/16     1       98    25     24.0
14   01/17    -2       28    25     24.0
15   01/17    -2       65    42     17.0
16   01/17     0       65    29     23.0
17   01/17    -1       79    29     26.0
18   01/18   -12       20    32     16.0
19   01/19   -13       19    44     17.0
20   01/19     0       20    33     23.0
21   01/19   -12       28    35     22.0
22   01/19     1       29    32     27.0
23   01/19   -15       52    46     11.0
24   01/19    -8       99    21     12.0
25   02/14    -2       74    27     16.0
26   02/15     1       19    46     16.0
27   02/15    -8       36    38     21.0
28   02/16    -5       34    45     23.0
29   02/16   -13       55    39     14.0
..     ...   ...      ...   ...      ...
870  03/15    -8       28    44     25.0
871  02/17     1       12    27     22.0
872  09/18   -10       73    32     25.0
873  08/14    -1       76    29     25.0
874  03/14    -4       25    27     21.0
875  12/16     2       43    20     18.0
876  07/17    -2        7    37     22.0
877  09/16     0       11    19     13.0
878  12/19     1       76    20     13.0
879  08/18   -13       23    30     12.0
880  02/17    -8       23    28     17.0
881  03/16    -2       61    21     10.0
882  12/19    -6       21    28     10.0
883  09/19   -10        8    18     17.0
884  05/14     0       21    42     27.0
885  07/18    -9        4    38     15.0
886  03/18    -6       94    40     10.0
887  06/15     0       23    26     13.0
888  01/17    -7       18    13     12.0
889  02/16   -15       72    14     11.0
890  01/14    -5       66    11     10.0
891  01/14     2       72    46     19.0
892  10/18    -8       50    43     24.0
893  05/19    -9       89    25     17.0
894  09/16   -10        8    26     19.0
895  02/16   -13       17    38     28.0
896  10/14     0       55    16     15.0
897  09/16   -15       19    35     12.0
898  03/19    -4       63    26     11.0
899  06/17    -1       18    44     24.0

[900 rows x 5 columns]

In [32]:
pluie.head()

    saison  annee terrain  precipitation
0  automne     16      34           79.0
1  automne     15      17          105.0
2  automne     16      42         1520.0
3  automne     99      16           18.0
4  automne     15      30         2140.0

In [33]:
pluie.dtypes

saison            object
annee              int64
terrain           object
precipitation    float64
dtype: object

In [34]:
pluie['terrain'] = pd.to_numeric(pluie['terrain'], errors='coerce')
pluie.dtypes

saison            object
annee              int64
terrain          float64
precipitation    float64
dtype: object

In [35]:
pluie['saison'] = pluie['saison'].astype(str)

In [36]:
pluie.dtypes

saison            object
annee              int64
terrain          float64
precipitation    float64
dtype: object

In [37]:
a=lambda x: str(x)
pluie['saison'].apply(a)

0      automne
1      automne
2      automne
3      automne
4      automne
5      automne
6      automne
7      automne
8      automne
9      automne
10     automne
11     automne
12     automne
13     automne
14     automne
15     automne
16     automne
17     automne
18     automne
19     automne
20     automne
21     automne
22     automne
23     automne
24     automne
25     automne
26     automne
27     automne
28     automne
29     automne
        ...
670        ete
671        ete
672        ete
673        ete
674        ete
675        ete
676        ete
677        ete
678        ete
679        ete
680        ete
681        ete
682        ete
683        ete
684        ete
685        ete
686        ete
687        ete
688        ete
689        ete
690        ete
691        ete
692        ete
693        ete
694        ete
695        ete
696        ete
697        ete
698        ete
699        ete
Name: saison, Length: 700, dtype: object

In [38]:
pluie.dtypes

saison            object
annee              int64
terrain          float64
precipitation    float64
dtype: object

In [39]:
pluie['precipitation'].loc[(pluie['precipitation'] > 2300) & (pluie['precipitation'] < 5500) & (pluie['saison'] == 'automne')] = pluie['precipitation']/10

C:\Users\Dell\Miniconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [40]:
pluie

      saison  annee  terrain  precipitation
0    automne     16     34.0           79.0
1    automne     15     17.0          105.0
2    automne     16     42.0         1520.0
3    automne     99     16.0           18.0
4    automne     15     30.0         2140.0
5    automne     16      2.0           88.0
6    automne     18      3.0           27.0
7    automne     18     28.0           30.0
8    automne     15     45.0          162.0
9    automne     56     42.0          149.0
10   automne     15     46.0           95.0
11   automne     18     49.0           58.0
12   automne     17     15.0          203.0
13   automne     15     23.0         1740.0
14   automne     15      4.0          113.0
15   automne     17     16.0           25.0
16   automne     15     12.0          105.0
17   automne     17     47.0          112.0
18   automne     16      6.0           85.0
19   automne     16     10.0          101.0
20   automne     16      8.0           52.0
21   automne     16     10.0          205.0
22   automne     15      3.0          148.0
23   automne     15     39.0         2020.0
24   automne     16     47.0           44.0
25   automne     15      4.0          155.0
26   automne     17     36.0         1730.0
27   automne     17      7.0          101.0
28   automne     18     19.0           34.0
29   automne     17     15.0           13.0
..       ...    ...      ...            ...
670      ete     17     92.0           18.0
671      ete     17     54.0           43.0
672      ete     17     54.0         3500.0
673      ete     17     70.0           13.0
674      ete     17     58.0           25.0
675      ete     17     90.0           50.0
676      ete     18     52.0           36.0
677      ete     17     68.0           50.0
678      ete     18     79.0           42.0
679      ete     18     66.0         2900.0
680      ete     17     98.0         2800.0
681      ete     17     97.0           35.0
682      ete     17     86.0           43.0
683      ete     17     92.0           42.0
684      ete     18     87.0           37.0
685      ete     17     69.0           12.0
686      ete     17     56.0           48.0
687      ete     17     78.0           12.0
688      ete     18     51.0           17.0
689      ete     18     68.0           15.0
690      ete     18     51.0           23.0
691      ete     17     73.0           45.0
692      ete     18     97.0           50.0
693      ete     17     82.0           15.0
694      ete     18     67.0           31.0
695      ete     18     69.0           27.0
696      ete     17     81.0         4900.0
697      ete     17     91.0         4700.0
698      ete     18     96.0           35.0
699      ete     17     90.0           42.0

[700 rows x 4 columns]

In [41]:
pluie['precipitation'].loc[(pluie['precipitation'] > 2300) & (pluie['precipitation'] < 5500) & (pluie['saison'] == 'ete')] = pluie['precipitation']/100

C:\Users\Dell\Miniconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [42]:
pluie

      saison  annee  terrain  precipitation
0    automne     16     34.0           79.0
1    automne     15     17.0          105.0
2    automne     16     42.0         1520.0
3    automne     99     16.0           18.0
4    automne     15     30.0         2140.0
5    automne     16      2.0           88.0
6    automne     18      3.0           27.0
7    automne     18     28.0           30.0
8    automne     15     45.0          162.0
9    automne     56     42.0          149.0
10   automne     15     46.0           95.0
11   automne     18     49.0           58.0
12   automne     17     15.0          203.0
13   automne     15     23.0         1740.0
14   automne     15      4.0          113.0
15   automne     17     16.0           25.0
16   automne     15     12.0          105.0
17   automne     17     47.0          112.0
18   automne     16      6.0           85.0
19   automne     16     10.0          101.0
20   automne     16      8.0           52.0
21   automne     16     10.0          205.0
22   automne     15      3.0          148.0
23   automne     15     39.0         2020.0
24   automne     16     47.0           44.0
25   automne     15      4.0          155.0
26   automne     17     36.0         1730.0
27   automne     17      7.0          101.0
28   automne     18     19.0           34.0
29   automne     17     15.0           13.0
..       ...    ...      ...            ...
670      ete     17     92.0           18.0
671      ete     17     54.0           43.0
672      ete     17     54.0           35.0
673      ete     17     70.0           13.0
674      ete     17     58.0           25.0
675      ete     17     90.0           50.0
676      ete     18     52.0           36.0
677      ete     17     68.0           50.0
678      ete     18     79.0           42.0
679      ete     18     66.0           29.0
680      ete     17     98.0           28.0
681      ete     17     97.0           35.0
682      ete     17     86.0           43.0
683      ete     17     92.0           42.0
684      ete     18     87.0           37.0
685      ete     17     69.0           12.0
686      ete     17     56.0           48.0
687      ete     17     78.0           12.0
688      ete     18     51.0           17.0
689      ete     18     68.0           15.0
690      ete     18     51.0           23.0
691      ete     17     73.0           45.0
692      ete     18     97.0           50.0
693      ete     17     82.0           15.0
694      ete     18     67.0           31.0
695      ete     18     69.0           27.0
696      ete     17     81.0           49.0
697      ete     17     91.0           47.0
698      ete     18     96.0           35.0
699      ete     17     90.0           42.0

[700 rows x 4 columns]

In [43]:
p = pluie.loc[(pluie['saison'] == 'hiver') & (pluie['annee'] == 18)]

In [44]:
pluie['precipitation'].loc[(pluie['precipitation'] > 5500) & (pluie['annee'].duplicated() == True) & (pluie['saison'] == 'hiver')]= p['precipitation'].mean()

C:\Users\Dell\Miniconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [45]:
p['precipitation']

200         238.0
203         246.0
209         249.0
214         153.0
216         128.0
217    11111111.0
224         161.0
225         172.0
230         222.0
242         253.0
246         135.0
248         212.0
249          77.0
254         256.0
255         178.0
262         143.0
265         169.0
275         127.0
283         233.0
288         176.0
291         204.0
293         186.0
295         110.0
296         172.0
Name: precipitation, dtype: float64

In [46]:
for i in range(len(pluie)):
    if pluie.terrain[i] == "soixante sept":
        pluie.terrain[i] = 67
    if pluie.terrain[i] == "dix sept":
        pluie.terrain[i] = 17
    if pluie.terrain[i] == "treize":
        pluie.terrain[i] = 13
    if pluie.terrain[i] == "vingt cinq":
        pluie.terrain[i] = 25
    if pluie.terrain[i] == "trente trois":
        pluie.terrain[i] = 33
    if pluie.terrain[i] == "quarante sept":
        pluie.terrain[i] = 47
    if pluie.terrain[i] == "quinze":
        pluie.terrain[i] = 15
    if pluie.terrain[i] == "quarante quatre":
        pluie.terrain[i] = 44
    if pluie.terrain[i] == "quarante et un":
        pluie.terrain[i] = 41
    if pluie.terrain[i] == "quatre vingt":
        pluie.terrain[i] = 80
    if pluie.terrain[i] == "soixante neuf":
        pluie.terrain[i] = 69

In [47]:
pluie

      saison  annee  terrain  precipitation
0    automne     16     34.0           79.0
1    automne     15     17.0          105.0
2    automne     16     42.0         1520.0
3    automne     99     16.0           18.0
4    automne     15     30.0         2140.0
5    automne     16      2.0           88.0
6    automne     18      3.0           27.0
7    automne     18     28.0           30.0
8    automne     15     45.0          162.0
9    automne     56     42.0          149.0
10   automne     15     46.0           95.0
11   automne     18     49.0           58.0
12   automne     17     15.0          203.0
13   automne     15     23.0         1740.0
14   automne     15      4.0          113.0
15   automne     17     16.0           25.0
16   automne     15     12.0          105.0
17   automne     17     47.0          112.0
18   automne     16      6.0           85.0
19   automne     16     10.0          101.0
20   automne     16      8.0           52.0
21   automne     16     10.0          205.0
22   automne     15      3.0          148.0
23   automne     15     39.0         2020.0
24   automne     16     47.0           44.0
25   automne     15      4.0          155.0
26   automne     17     36.0         1730.0
27   automne     17      7.0          101.0
28   automne     18     19.0           34.0
29   automne     17     15.0           13.0
..       ...    ...      ...            ...
670      ete     17     92.0           18.0
671      ete     17     54.0           43.0
672      ete     17     54.0           35.0
673      ete     17     70.0           13.0
674      ete     17     58.0           25.0
675      ete     17     90.0           50.0
676      ete     18     52.0           36.0
677      ete     17     68.0           50.0
678      ete     18     79.0           42.0
679      ete     18     66.0           29.0
680      ete     17     98.0           28.0
681      ete     17     97.0           35.0
682      ete     17     86.0           43.0
683      ete     17     92.0           42.0
684      ete     18     87.0           37.0
685      ete     17     69.0           12.0
686      ete     17     56.0           48.0
687      ete     17     78.0           12.0
688      ete     18     51.0           17.0
689      ete     18     68.0           15.0
690      ete     18     51.0           23.0
691      ete     17     73.0           45.0
692      ete     18     97.0           50.0
693      ete     17     82.0           15.0
694      ete     18     67.0           31.0
695      ete     18     69.0           27.0
696      ete     17     81.0           49.0
697      ete     17     91.0           47.0
698      ete     18     96.0           35.0
699      ete     17     90.0           42.0

[700 rows x 4 columns]

In [48]:
def test(df):
    if df['precipitation'] > 5500:
        df['precipitation'] = pluie.loc[(pluie['annee'] == df.annee) & (pluie['saison'] == df.saison) 
        & (pluie['precipitation'] < 5500)].precipitation.mean()
    return df;

In [49]:
pluie = pluie.apply(test, axis = 1)
pluie['precipitation'] = pluie['precipitation'].astype('int64')

ValueError: Cannot convert non-finite values (NA or inf) to integer